version: '3'
services:
  bourne:
    build: .
    command: ["./wait-for-services.sh", "pdm", "run", "uvicorn", "bourne.main:app", "--host", "0.0.0.0"]
    environment:
      - SCYLLA_HOST=scylla
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      scylla:
          condition: service_healthy
      kafka:
          condition: service_started

  scylla:
    image: scylladb/scylla:5.4.0
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES" ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "9042:9042"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181