name: Bourne CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylla:
        image: scylladb/scylla:5.4.9
        ports:
          - "9042:9042"
        options: >-
          --health-cmd "cqlsh -e 'DESCRIBE KEYSPACES'"
          --health-interval 10s
          --health-timeout 20s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cassandra tools (cqlsh)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install cqlsh

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PDM
        run: pip install pdm

      - name: Cache PDM dependencies
        uses: actions/cache@v3
        with:
          path: |
            .venv
            __pypackages__
          key: pdm-${{ hashFiles('pdm.lock') }}

      - name: Install dependencies
        run: |
          pdm install -G dev
          pdm run pip install --upgrade pip

      - name: Run tests
        env:
          SCYLLA_HOST: localhost
        run: pdm run pytest -v tests/

      - name: Code formatting (black)
        run: pdm run black --check src tests

      - name: Type checking (mypy)
        run: pdm run mypy src

      - name: Linting (ruff)
        run: pdm run ruff check src tests